Repository alloy-rs/alloy, pull requests merged in 2024-09, with the labels that each got.

#1275 Add trait methods `cumulative_gas_used` and `state_root` to `ReceiptResponse`
  crates/network-primitives/src/traits.rs
  crates/rpc-types-eth/src/transaction/receipt.rs
Labels: debt

#1277 feat: add serde for NumHash
  crates/eips/src/eip1898.rs
Labels: enhancement

#1303 feat(rpc-types-beacon): `SignedBidSubmissionV4`
  crates/eips/src/eip7002.rs
  crates/rpc-types-beacon/src/relay.rs
  crates/rpc-types-engine/src/payload.rs
Labels: enhancement

#788 feature: ProviderCall
  crates/contract/src/call.rs
  crates/contract/src/eth_call.rs
  crates/json-rpc/src/request.rs
  crates/provider/src/ext/trace.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider/caller.rs
  crates/provider/src/provider/eth_call.rs
  crates/provider/src/provider/mod.rs
  crates/provider/src/provider/prov_call.rs
  crates/provider/src/provider/trait.rs
  crates/provider/src/provider/with_block.rs
  crates/rpc-client/src/batch.rs
  crates/rpc-client/src/call.rs
Labels: enhancement, debt

#1327 Add `OperationType::OpEofCreate`
  crates/rpc-types-trace/src/otterscan.rs
Labels: enhancement

#1348 fix(serde): encode optional types as Some
  crates/serde/src/num.rs
  crates/serde/src/quantity.rs
Labels: bug

#1395 Auto-impl `alloy_consensus::TxReceipt` for ref
  crates/consensus/Cargo.toml
  crates/consensus/src/receipt/mod.rs
Labels: debt

#1394 Return static `Eip658Value` from `TxReceipt` trait method
  crates/consensus/src/receipt/any.rs
  crates/consensus/src/receipt/envelope.rs
  crates/consensus/src/receipt/mod.rs
  crates/consensus/src/receipt/receipts.rs
Labels: debt

#1387 Add supertrait alloy_consensus::Transaction to RPC TransactionResponse
  crates/consensus/src/transaction/mod.rs
  crates/network-primitives/Cargo.toml
  crates/network-primitives/src/traits.rs
  crates/rpc-types-eth/src/transaction/mod.rs
  crates/signer-trezor/src/signer.rs
Labels: debt

#1397 feat(consensus): bincode compatibility for header and transaction types
  crates/consensus/Cargo.toml
  crates/consensus/src/header.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/legacy.rs
  crates/consensus/src/transaction/mod.rs
Labels: enhancement

#1401 chore(consensus): less derives for bincode compatible types
  crates/consensus/src/header.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/legacy.rs
Labels: enhancement
