Repository alloy-rs/alloy, pull requests merged in 2024-04, with the labels that each got.

#443 chore: remove redundant JsonU256 from ethers
  crates/genesis/src/lib.rs
  crates/rpc-types/src/eth/admin.rs
  crates/serde/src/lib.rs
  crates/serde/src/ttd.rs
Labels: debt

#434 feat: add Http::new for reqwest::Client
  crates/transport-http/src/lib.rs
  crates/transport-http/src/reqwest.rs
Labels: enhancement

#426 Feature: Joinable transaction fillers
  crates/alloy/Cargo.toml
  crates/contract/README.md
  crates/eips/src/eip2930.rs
  crates/json-rpc/src/error.rs
  crates/network/src/any/builder.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/signer.rs
  crates/network/src/lib.rs
  crates/network/src/transaction/builder.rs
  crates/network/src/transaction/signer.rs
  crates/provider/Cargo.toml
  crates/provider/src/builder.rs
  crates/provider/src/fillers/chain_id.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/join_fill.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
  crates/provider/src/layers/gas.rs
  crates/provider/src/layers/mod.rs
  crates/provider/src/layers/nonce.rs
  crates/provider/src/layers/signer.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider.rs
  crates/rpc-types/src/eth/transaction/request.rs
  crates/transport/src/common.rs
Labels: enhancement, debt

#486 docs(provider): add examples to `raw_request{,dyn}`
  crates/provider/src/provider.rs
  crates/rpc-types/src/eth/log.rs
  crates/rpc-types/src/eth/transaction/receipt.rs
Labels: documentation

#494 chore: add helper for next block base fee
  crates/eips/src/eip1559/basefee.rs
Labels: enhancement

#496 chore: add missing eq derives
  crates/rpc-types/src/eth/syncing.rs
Labels: enhancement

#497 docs: update txtype docs
  crates/rpc-types/src/eth/transaction/tx_type.rs
Labels: documentation

#504 chore: clippy, warnings
  crates/consensus/src/transaction/envelope.rs
  crates/contract/src/event.rs
  crates/eips/src/eip4895.rs
  crates/eips/src/lib.rs
  crates/pubsub/src/managers/active_sub.rs
Labels: enhancement

#515 Prestwich/signer multiplex
  crates/network/src/any/builder.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/signer.rs
  crates/network/src/transaction/signer.rs
  crates/signer-aws/src/signer.rs
  crates/signer-gcp/src/signer.rs
  crates/signer-ledger/src/signer.rs
  crates/signer-trezor/src/signer.rs
  crates/signer-wallet/src/lib.rs
Labels: enhancement, debt

#508 feat: port helpers for accesslist
  crates/eips/src/eip2930.rs
Labels: enhancement

#525 feat: add BaseFeeParams::new
  crates/eips/src/eip1559/basefee.rs
Labels: enhancement

#526 feat: add rpc-types-anvil
  Cargo.toml
  crates/rpc-types-anvil/Cargo.toml
  crates/rpc-types-anvil/README.md
  crates/rpc-types-anvil/src/lib.rs
Labels: enhancement

#537 docs: fix 404s on docs site via absolute paths
  README.md
Labels: documentation

#550 fix: conflict between to change and debug tests
  crates/provider/src/debug.rs
Labels: bug

#431 feat: refactor request builder workflow
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/typed.rs
  crates/network/src/any/builder.rs
  crates/network/src/any/mod.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/mod.rs
  crates/network/src/lib.rs
  crates/network/src/transaction/builder.rs
  crates/network/src/transaction/mod.rs
  crates/network/src/transaction/signer.rs
  crates/provider/src/provider.rs
  crates/rpc-types/src/eth/transaction/mod.rs
  crates/rpc-types/src/eth/transaction/request.rs
Labels: debt

#557 feat: add prague engine types
  crates/eips/src/eip6110.rs
  crates/eips/src/lib.rs
  crates/rpc-types-engine/Cargo.toml
  crates/rpc-types-engine/src/exit.rs
  crates/rpc-types-engine/src/lib.rs
  crates/rpc-types-engine/src/payload.rs
Labels: enhancement

#559 fix: add more generics to any and receipt with bloom
  crates/consensus/src/receipt/any.rs
  crates/consensus/src/receipt/receipts.rs
  crates/rpc-types/src/eth/log.rs
Labels: bug, debt

#555 fix: signer fills from if unset
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
Labels: enhancement

#556 fix: override txtype during submission prep
  crates/network/src/ethereum/builder.rs
  crates/network/src/transaction/builder.rs
Labels: enhancement, debt

#565 chore: move BlockId type to alloy-eip
  crates/eips/src/eip1898.rs
  crates/eips/src/lib.rs
  crates/rpc-types/src/eth/block.rs
Labels: enhancement

#569 feature: WalletProvider
  crates/network/src/ethereum/signer.rs
  crates/network/src/transaction/signer.rs
  crates/provider/src/fillers/join_fill.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/fillers/signer.rs
  crates/provider/src/lib.rs
  crates/provider/src/wallet.rs
Labels: enhancement

#581 feat: bubble up set_subscription_status
  crates/rpc-client/src/call.rs
Labels: enhancement

#598 feature: passthrough methods on txenvelope
  crates/consensus/src/transaction/envelope.rs
Labels: enhancement

#609 chore: b'a'
  crates/transport-ipc/src/lib.rs
Labels: debt

#621 fix: don't serialize nulls in tx request
  crates/rpc-types/src/eth/transaction/request.rs
Labels: bug, debt

#620 fix: admin_peerInfo, bump geth
  .github/scripts/install_test_binaries.sh
  crates/rpc-types/src/eth/admin.rs
Labels: bug

#614 fix: better tx receipt mitigation
  crates/provider/src/heart.rs
Labels: bug

#611 feature: AnvilProvider
  crates/provider/src/builder.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
  crates/provider/src/layers/anvil.rs
  crates/provider/src/layers/mod.rs
  crates/provider/src/lib.rs
  crates/provider/src/wallet.rs
Labels: enhancement

#627 docs: add required softwares to run tests in Contributing.md
  CONTRIBUTING.md
Labels: documentation

#637 fix: signer filler now propagates missing keys from builder
  crates/network/src/transaction/builder.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
Labels: bug, debt

#632 [Refactor] Delete the internal-test-utils crate
  crates/contract/Cargo.toml
  crates/contract/src/call.rs
  crates/contract/src/event.rs
  crates/internal-test-utils/Cargo.toml
  crates/internal-test-utils/src/lib.rs
  crates/internal-test-utils/src/providers.rs
  crates/provider/Cargo.toml
  crates/provider/src/admin.rs
  crates/provider/src/builder.rs
  crates/provider/src/debug.rs
  crates/provider/src/fillers/chain_id.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
  crates/provider/src/layers/anvil.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider.rs
  crates/provider/src/txpool.rs
  crates/rpc-client/src/builtin.rs
  crates/serde/src/num.rs
Labels: debt

#644 [Refactor] Move Provider into its own module
  crates/provider/src/ext/admin.rs
  crates/provider/src/ext/debug.rs
  crates/provider/src/ext/mod.rs
  crates/provider/src/ext/txpool.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider/mod.rs
  crates/provider/src/provider/root.rs
  crates/provider/src/provider/sendable.rs
  crates/provider/src/provider/trait.rs
  crates/provider/src/provider/wallet.rs
Labels: debt

#648 fix: populate hashes after setting sidecar
  crates/network/src/ethereum/builder.rs
Labels: bug

#651 use `From<Address>` for `TxKind`
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/legacy.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/transaction/builder.rs
  crates/provider/src/provider/trait.rs
  crates/rpc-types/src/eth/transaction/request.rs
  crates/signer-ledger/src/signer.rs
  crates/signer-wallet/src/lib.rs
Labels: debt
