Repository alloy-rs/alloy, pull requests merged in 2024-10, with the labels that each got.

#1404 feat(consensus): bincode compatibility for EIP-7702
  Cargo.toml
  crates/consensus/Cargo.toml
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip7702.rs
  crates/consensus/src/transaction/mod.rs
  crates/eips/Cargo.toml
Labels: enhancement

#1461 chore: some small improvements
  crates/consensus/src/header.rs
  crates/eips/src/eip4844/builder.rs
  crates/node-bindings/src/nodes/reth.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/provider/eth_call.rs
  crates/rpc-client/src/batch.rs
  crates/rpc-types-engine/src/jwt.rs
  crates/rpc-types-eth/src/filter.rs
  crates/rpc-types-trace/src/filter.rs
  crates/rpc-types-trace/src/geth/mod.rs
Labels: debt

#1380 chore: update eip-7251 bytecode and address
  crates/eips/src/eip7251.rs
Labels: enhancement, blocked

#1457 feat: add missing eth_getTransaction methods
  crates/provider/src/provider/trait.rs
Labels: enhancement

#1501 consensus: rm redundant root hash definitions
  crates/consensus/src/header.rs
  crates/consensus/src/lib.rs
Labels: debt

#1379 chore: rename requests root to requests hash
  crates/consensus/src/header.rs
  crates/rpc-types-eth/src/block.rs
Labels: enhancement

#1508 fix: use `requests_hash`
  crates/consensus/src/header.rs
Labels: bug

#1535 feat: derive serde for `ExecutionPayloadSidecar`
  crates/rpc-types-engine/src/cancun.rs
  crates/rpc-types-engine/src/sidecar.rs
Labels: enhancement

#1528 fix: correct implementations of Encodable and Decodable for sidecars
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/envelope.rs
  crates/eips/src/eip2718.rs
  crates/eips/src/eip4844/sidecar.rs
Labels: bug

#1548 feat: add osaka time to genesis
  crates/genesis/src/lib.rs
Labels: enhancement

#1564 docs: expand on what `Requests` contains
  crates/eips/src/eip7685.rs
Labels: documentation

#1536 fix: Fix typo in RecommendedFillers associated type
  crates/provider/src/builder.rs
  crates/provider/src/fillers/mod.rs
Labels: blocked
