Repository alloy-rs/alloy, pull requests merged in 2024-08, with the labels that each got.

#1125 feat: add authorization list to TransactionRequest
  crates/rpc-types-eth/src/transaction/mod.rs
  crates/rpc-types-eth/src/transaction/request.rs
Labels: enhancement

#1137 chore: add missing 7702 check
  crates/network/src/ethereum/builder.rs
Labels: enhancement

#1150 feat(geth/trace): add field log.position
  crates/rpc-types-trace/src/geth/call.rs
  crates/rpc-types-trace/test_data/call_tracer/with_log.json
Labels: enhancement

#1172 Add trait methods for constructing `alloy_rpc_types_eth::Transaction` to `alloy_consensus::Transaction`
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/eip7702.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/legacy.rs
  crates/consensus/src/transaction/mod.rs
  crates/consensus/src/transaction/typed.rs
Labels: debt

#1178 feat(rpc-types): `debug_executionWitness`
  Cargo.toml
  README.md
  crates/rpc-types-debug/CHANGELOG.md
  crates/rpc-types-debug/Cargo.toml
  crates/rpc-types-debug/README.md
  crates/rpc-types-debug/src/debug.rs
  crates/rpc-types-debug/src/lib.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/lib.rs
Labels: enhancement

#1189 Add emhane to codeowners
  .github/CODEOWNERS
Labels: meta

#1197 chore(consensus): Add missing getter trait methods for `alloy_consensus::Transaction`
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/eip7702.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/legacy.rs
  crates/consensus/src/transaction/mod.rs
  crates/consensus/src/transaction/typed.rs
Labels: debt

#1167 chore: bump core and rm ssz feat
  Cargo.toml
  crates/alloy/Cargo.toml
  crates/eips/Cargo.toml
  crates/rpc-types-beacon/Cargo.toml
  crates/rpc-types-engine/Cargo.toml
  crates/rpc-types-eth/Cargo.toml
  crates/rpc-types/Cargo.toml
Labels: blocked

#1198 Implement conversion between signature types
  crates/rpc-types-eth/src/transaction/signature.rs
Labels: debt

#1108 feat(alloy-provider): add abstraction for `NonceFiller` behavior
  crates/provider/src/builder.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/fillers/nonce.rs
Labels: enhancement

#1210 fix: value of TxEip1559.ty
  crates/consensus/src/transaction/eip1559.rs
Labels: bug

#1214 eip7702: implement `tx_type` for `TxEip7702`
  crates/consensus/src/transaction/eip7702.rs
Labels: enhancement
