Repository alloy-rs/alloy, pull requests merged in 2024-01, with the labels that each got.

#116 chore: correct doc typo
  crates/json-rpc/src/packet.rs
Labels: documentation

#117 bug: correct `is_create` condition
  crates/rpc-trace-types/src/parity.rs
Labels: bug

#135 fix: use port 0 for anvil by default
  crates/node-bindings/src/anvil.rs
Labels: debt

#149 feat: alloy-dyn-contract
  Cargo.toml
  crates/dyn-contract/Cargo.toml
  crates/dyn-contract/README.md
  crates/dyn-contract/src/call.rs
  crates/dyn-contract/src/error.rs
  crates/dyn-contract/src/instance.rs
  crates/dyn-contract/src/interface.rs
  crates/dyn-contract/src/lib.rs
  crates/providers/src/provider.rs
  crates/rpc-types/src/eth/call.rs
Labels: enhancement
