Repository alloy-rs/alloy, pull requests merged in 2024-03, with the labels that each got.

#179 ClientRefs, Poller, and Streams
  .github/workflows/ci.yml
  Cargo.toml
  crates/contract/src/call.rs
  crates/contract/src/instance.rs
  crates/contract/src/lib.rs
  crates/json-rpc/src/error.rs
  crates/json-rpc/src/request.rs
  crates/providers/Cargo.toml
  crates/providers/src/builder.rs
  crates/providers/src/chain.rs
  crates/providers/src/heart.rs
  crates/providers/src/lib.rs
  crates/providers/src/new.rs
  crates/providers/src/tmp.rs
  crates/pubsub/Cargo.toml
  crates/pubsub/src/service.rs
  crates/pubsub/src/sub.rs
  crates/rpc-client/Cargo.toml
  crates/rpc-client/src/batch.rs
  crates/rpc-client/src/call.rs
  crates/rpc-client/src/client.rs
  crates/rpc-client/src/lib.rs
  crates/rpc-client/src/poller.rs
  crates/signer-aws/src/signer.rs
  crates/transport-ipc/src/lib.rs
  crates/transport-ws/src/lib.rs
  crates/transport-ws/src/native.rs
  crates/transport-ws/src/wasm.rs
  crates/transport/src/error.rs
  crates/transport/src/lib.rs
  crates/transport/src/trait.rs
Labels: enhancement

#254 Convert non-200 http responses into errors
  crates/transport-http/src/hyper.rs
  crates/transport-http/src/reqwest.rs
Labels: bug

#190 feat: network abstraction and transaction builder
  .github/workflows/ci.yml
  Cargo.toml
  crates/consensus/Cargo.toml
  crates/consensus/README.md
  crates/consensus/src/header.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/receipt/mod.rs
  crates/consensus/src/receipt/receipts.rs
  crates/consensus/src/sealed.rs
  crates/consensus/src/signed.rs
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/legacy.rs
  crates/consensus/src/transaction/mod.rs
  crates/consensus/src/transaction/typed.rs
  crates/contract/Cargo.toml
  crates/contract/src/call.rs
  crates/contract/src/instance.rs
  crates/contract/src/interface.rs
  crates/contract/src/lib.rs
  crates/eips/src/eip1559/helpers.rs
  crates/network/Cargo.toml
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/mod.rs
  crates/network/src/ethereum/signer.rs
  crates/network/src/lib.rs
  crates/network/src/receipt.rs
  crates/network/src/transaction/builder.rs
  crates/network/src/transaction/common.rs
  crates/network/src/transaction/mod.rs
  crates/network/src/transaction/signer.rs
  crates/providers/Cargo.toml
  crates/providers/src/builder.rs
  crates/providers/src/chain.rs
  crates/providers/src/lib.rs
  crates/providers/src/new.rs
  crates/providers/src/signer.rs
  crates/providers/src/tmp.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/eth/transaction/mod.rs
  crates/rpc-types/src/eth/transaction/optimism.rs
  crates/rpc-types/src/eth/transaction/request.rs
  crates/signer-aws/Cargo.toml
  crates/signer-aws/src/signer.rs
  crates/signer-gcp/Cargo.toml
  crates/signer-gcp/src/signer.rs
  crates/signer-ledger/Cargo.toml
  crates/signer-ledger/src/signer.rs
  crates/signer-trezor/src/signer.rs
  crates/signer-trezor/src/types.rs
  crates/signer/Cargo.toml
  crates/signer/README.md
  crates/signer/src/lib.rs
  crates/signer/src/signer.rs
  crates/signer/src/wallet/mod.rs
  crates/signer/src/wallet/private_key.rs
  crates/signer/src/wallet/yubi.rs
Labels: enhancement, debt

#280 chore: const fns
  crates/providers/src/builder.rs
  crates/providers/src/heart.rs
  crates/providers/src/lib.rs
  crates/providers/src/signer.rs
Labels: debt

#282 chore: debug/copy/clone derives
  crates/providers/src/builder.rs
  crates/providers/src/heart.rs
  crates/providers/src/signer.rs
Labels: debt

#281 docs: more docs in `alloy-providers`
  crates/provider/src/builder.rs
  crates/provider/src/new.rs
Labels: documentation

#277 feat: `trace_call` and `trace_callMany`
  crates/provider/src/new.rs
Labels: enhancement

#279 refactor: remove `async_trait` in tx builder
  crates/network/src/ethereum/builder.rs
  crates/network/src/transaction/builder.rs
Labels: debt

#276 feat: nonce filling layer
  crates/provider/Cargo.toml
  crates/provider/src/builder.rs
  crates/provider/src/layers/mod.rs
  crates/provider/src/layers/nonce.rs
  crates/provider/src/layers/signer.rs
  crates/provider/src/lib.rs
  crates/provider/src/new.rs
Labels: enhancement

#284 feat: derive `Hash` for `TypedTransaction`
  crates/consensus/Cargo.toml
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/typed.rs
Labels: enhancement

#250 Feat: 4844 SidecarBuilder
  crates/consensus/src/lib.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/eip4844/builder.rs
  crates/consensus/src/transaction/eip4844/utils.rs
  crates/consensus/src/transaction/mod.rs
  crates/eips/src/eip4844.rs
Labels: enhancement

#331 fix: force clippy to stable
  .github/workflows/ci.yml
Labels: enhancement

#344 fix(transaction-request): Support HEX `TransactionRequest.chain_id`
  crates/rpc-types/src/eth/transaction/request.rs
Labels: bug

#353 refactor: rename to reqd_confs
  crates/provider/src/heart.rs
  crates/provider/src/provider.rs
Labels: enhancement

#326 feat(layers): GasEstimationLayer
  crates/provider/src/layers/gas.rs
  crates/provider/src/layers/mod.rs
Labels: enhancement

#366 fix: missing to in 4844 conversion
  crates/rpc-types/src/eth/transaction/error.rs
Labels: bug

#363 fix: remove app-layer usage of transport error
  crates/json-rpc/src/error.rs
  crates/provider/src/heart.rs
  crates/provider/src/layers/gas.rs
  crates/provider/src/provider.rs
  crates/provider/src/utils.rs
  crates/transport/src/error.rs
Labels: bug, debt

#339 feat: `Provider::subscribe_logs`
  crates/contract/Cargo.toml
  crates/contract/src/event.rs
  crates/contract/src/lib.rs
  crates/provider/src/provider.rs
Labels: enhancement

#372 chore: bump core
  Cargo.toml
  crates/signer-aws/Cargo.toml
Labels: enhancement

#360 feat: versioned hashes without kzg
  crates/consensus/Cargo.toml
  crates/consensus/src/transaction/eip4844.rs
Labels: enhancement

#375 feat: re-export EnvKzgSettings
  crates/consensus/Cargo.toml
  crates/consensus/src/lib.rs
  crates/consensus/src/transaction/eip4844/builder.rs
Labels: enhancement

#401 chore: dedupe blob in consensus and rpc
  crates/consensus/src/lib.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/mod.rs
  crates/rpc-engine-types/Cargo.toml
  crates/rpc-engine-types/src/lib.rs
  crates/rpc-engine-types/src/payload.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/eth/transaction/blob.rs
  crates/rpc-types/src/eth/transaction/kzg.rs
  crates/rpc-types/src/eth/transaction/mod.rs
Labels: enhancement, debt

#420 docs: add aliases to `get_transaction_count`
  crates/provider/src/provider.rs
Labels: documentation

#417 chore: rearrange field order
  crates/rpc-trace-types/src/geth/mod.rs
Labels: enhancement

#405 feat: implement `admin_trait`
  crates/provider/src/admin.rs
  crates/provider/src/lib.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/eth/admin.rs
  crates/rpc-types/src/eth/mod.rs
Labels: enhancement

#383 feat: add `AnyNetwork`
  crates/network/src/any/builder.rs
  crates/network/src/any/mod.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/mod.rs
  crates/network/src/lib.rs
  crates/rpc-types/src/eth/transaction/mod.rs
  crates/rpc-types/src/eth/transaction/receipt.rs
  crates/rpc-types/src/eth/transaction/request.rs
  crates/rpc-types/src/lib.rs
  crates/rpc-types/src/with_other.rs
Labels: enhancement

#287 feat: add initial EIP-7547 engine types
  Cargo.toml
  crates/eip7547/Cargo.toml
  crates/eip7547/README.md
  crates/eip7547/src/constants.rs
  crates/eip7547/src/lib.rs
  crates/eip7547/src/summary.rs
Labels: enhancement

#396 feature: embed primitives Log in rpc Log and consensus Receipt in rpc Receipt
  crates/consensus/src/receipt/envelope.rs
  crates/consensus/src/receipt/mod.rs
  crates/consensus/src/receipt/receipts.rs
  crates/consensus/src/transaction/envelope.rs
  crates/contract/src/event.rs
  crates/provider/src/layers/gas.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/eth/log.rs
  crates/rpc-types/src/eth/transaction/receipt.rs
  crates/serde/src/bool.rs
  crates/serde/src/lib.rs
Labels: debt
