Repository alloy-rs/alloy, pull requests merged in 2024-06, with the labels that each got.

#822 chore: add engine api v4 capabilities
  crates/rpc-types-engine/src/lib.rs
Labels: enhancement

#837 [Fix] Mark `Eip2718Error` as `non_exhaustive`
  crates/eips/src/eip2718.rs
Labels: debt

#841 [feat] Synchronous filling
  crates/provider/src/builder.rs
  crates/provider/src/fillers/chain_id.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/join_fill.rs
  crates/provider/src/fillers/mod.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/signer.rs
Labels: bug, debt

#848 Fix: Support pre-658 status codes
  crates/consensus/src/lib.rs
  crates/consensus/src/receipt/any.rs
  crates/consensus/src/receipt/envelope.rs
  crates/consensus/src/receipt/mod.rs
  crates/consensus/src/receipt/receipts.rs
  crates/consensus/src/receipt/status.rs
  crates/rpc-types/src/eth/transaction/receipt.rs
Labels: bug

#851 feat: send_envelope
  crates/provider/src/provider/trait.rs
Labels: enhancement

#869 [Fix] use Eip2718Error, add docs on different encodings
  crates/consensus/src/receipt/any.rs
  crates/consensus/src/receipt/envelope.rs
  crates/consensus/src/transaction/envelope.rs
  crates/eips/src/eip2718.rs
Labels: bug, debt

#899 feat: add getter methods for `FilterChanges`
  crates/rpc-types-eth/src/filter.rs
Labels: enhancement

#902 feat: derive serde for header
  crates/consensus/src/header.rs
Labels: enhancement

#903 chore(clippy): apply lint suggestions
  crates/consensus/src/receipt/status.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/typed.rs
  crates/json-rpc/src/common.rs
  crates/json-rpc/src/packet.rs
  crates/network/src/any/builder.rs
  crates/network/src/ethereum/builder.rs
  crates/provider/src/provider/trait.rs
  crates/pubsub/src/managers/in_flight.rs
  crates/rpc-types-engine/src/payload.rs
  crates/serde/src/num.rs
  crates/serde/src/quantity.rs
Labels: debt

#916 Convenience method for conversion from `BlockId` to `u64`
  crates/eips/src/eip1898.rs
Labels: enhancement

#914 docs: add per-crate changelogs
  CHANGELOG.md
  crates/alloy/CHANGELOG.md
  crates/consensus/CHANGELOG.md
  crates/contract/CHANGELOG.md
  crates/eip7547/CHANGELOG.md
  crates/eips/CHANGELOG.md
  crates/genesis/CHANGELOG.md
  crates/json-rpc/CHANGELOG.md
  crates/network/CHANGELOG.md
  crates/node-bindings/CHANGELOG.md
  crates/provider/CHANGELOG.md
  crates/pubsub/CHANGELOG.md
  crates/rpc-client/CHANGELOG.md
  crates/rpc-types-admin/CHANGELOG.md
  crates/rpc-types-anvil/CHANGELOG.md
  crates/rpc-types-beacon/CHANGELOG.md
  crates/rpc-types-engine/CHANGELOG.md
  crates/rpc-types-eth/CHANGELOG.md
  crates/rpc-types-trace/CHANGELOG.md
  crates/rpc-types-txpool/CHANGELOG.md
  crates/rpc-types/CHANGELOG.md
  crates/serde/CHANGELOG.md
  crates/signer-aws/CHANGELOG.md
  crates/signer-gcp/CHANGELOG.md
  crates/signer-ledger/CHANGELOG.md
  crates/signer-local/CHANGELOG.md
  crates/signer-trezor/CHANGELOG.md
  crates/signer/CHANGELOG.md
  crates/transport-http/CHANGELOG.md
  crates/transport-ipc/CHANGELOG.md
  crates/transport-ws/CHANGELOG.md
  crates/transport/CHANGELOG.md
  scripts/changelog.sh
Labels: documentation

#919 feat: add eip-7251 consolidation request
  crates/consensus/CHANGELOG.md
  crates/consensus/src/request.rs
  crates/eips/src/eip7251.rs
  crates/eips/src/lib.rs
Labels: enhancement

#922 chore: update changelogs for v0.1.1
  crates/alloy/CHANGELOG.md
  crates/consensus/CHANGELOG.md
  crates/contract/CHANGELOG.md
  crates/eip7547/CHANGELOG.md
  crates/eips/CHANGELOG.md
  crates/genesis/CHANGELOG.md
  crates/json-rpc/CHANGELOG.md
  crates/network/CHANGELOG.md
  crates/node-bindings/CHANGELOG.md
  crates/provider/CHANGELOG.md
  crates/pubsub/CHANGELOG.md
  crates/rpc-client/CHANGELOG.md
  crates/rpc-types-admin/CHANGELOG.md
  crates/rpc-types-anvil/CHANGELOG.md
  crates/rpc-types-beacon/CHANGELOG.md
  crates/rpc-types-engine/CHANGELOG.md
  crates/rpc-types-eth/CHANGELOG.md
  crates/rpc-types-trace/CHANGELOG.md
  crates/rpc-types-txpool/CHANGELOG.md
  crates/rpc-types/CHANGELOG.md
  crates/serde/CHANGELOG.md
  crates/signer-aws/CHANGELOG.md
  crates/signer-gcp/CHANGELOG.md
  crates/signer-ledger/CHANGELOG.md
  crates/signer-local/CHANGELOG.md
  crates/signer-trezor/CHANGELOG.md
  crates/signer/CHANGELOG.md
  crates/transport-http/CHANGELOG.md
  crates/transport-ipc/CHANGELOG.md
  crates/transport-ws/CHANGELOG.md
  crates/transport/CHANGELOG.md
Labels: documentation

#920 chore: don't self-host documentation anymore
  .github/workflows/ci.yml
Labels: enhancement

#934 chore: update eip-2935 bytecode and address
  crates/eips/CHANGELOG.md
  crates/eips/src/eip2935.rs
Labels: enhancement

#942 docs: update alloy-eips supported eip list
  crates/eips/README.md
Labels: documentation

#952 fix: enable tls12 in rustls
  Cargo.toml
  crates/provider/src/provider/trait.rs
Labels: bug

#955 fix: deserialization of null storage keys in AccessListItem
  crates/eips/src/eip2930.rs
  crates/serde/src/lib.rs
  crates/serde/src/optional.rs
Labels: enhancement

#960 feat(contract): implement Filter's builder methods on Event
  crates/contract/src/event.rs
  crates/rpc-types-eth/src/filter.rs
Labels: enhancement

#950 feat: add eip-7702 helpers
  crates/alloy/Cargo.toml
  crates/consensus/Cargo.toml
  crates/eips/Cargo.toml
  crates/eips/README.md
  crates/eips/src/eip6110.rs
  crates/eips/src/eip7251.rs
  crates/eips/src/eip7702/auth_list.rs
  crates/eips/src/eip7702/constants.rs
  crates/eips/src/eip7702/mod.rs
  crates/eips/src/lib.rs
  crates/rpc-types-eth/Cargo.toml
Labels: enhancement

#970 feat: move mev.rs from reth to rpc-types-mev
  Cargo.toml
  crates/rpc-types-mev/Cargo.toml
  crates/rpc-types-mev/README.md
  crates/rpc-types-mev/src/common.rs
  crates/rpc-types-mev/src/eth_calls.rs
  crates/rpc-types-mev/src/lib.rs
  crates/rpc-types-mev/src/mev_calls.rs
  crates/rpc-types-mev/src/stats.rs
  crates/rpc-types-mev/src/u256_numeric_string.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/lib.rs
Labels: enhancement
