Repository alloy-rs/alloy, pull requests merged in 2024-05, with the labels that each got.

#645 feat: eth_call builder
  crates/contract/src/call.rs
  crates/contract/src/eth_call.rs
  crates/contract/src/lib.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider/call.rs
  crates/provider/src/provider/mod.rs
  crates/provider/src/provider/trait.rs
Labels: enhancement

#653 chore(README): fix typo
  README.md
Labels: documentation

#654 docs: unhide `sol!` wrapper in meta crate
  crates/alloy/src/lib.rs
Labels: documentation

#663 fix(`README.md`): Add `alloy-signer-wallet` to crate list in readme
  README.md
Labels: documentation

#666 fix: more abstraction for block transactions
  crates/provider/src/provider/trait.rs
  crates/rpc-types/src/eth/block.rs
Labels: enhancement, debt

#672 chore: replace `ExitV1` with `WithdrawalRequest`
  crates/eips/src/eip7002.rs
  crates/eips/src/lib.rs
  crates/rpc-types-engine/src/exit.rs
  crates/rpc-types-engine/src/lib.rs
  crates/rpc-types-engine/src/payload.rs
Labels: debt

#673 feat: use alloy types for BlobTransactionSidecar
  crates/consensus/Cargo.toml
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/eip4844/builder.rs
  crates/consensus/src/transaction/envelope.rs
  crates/eips/Cargo.toml
  crates/eips/src/eip4844/mod.rs
  crates/eips/src/eip4844/sidecar.rs
Labels: debt

#668 feat: add eip-7685 requests root to header
  crates/consensus/src/header.rs
  crates/rpc-types/src/eth/block.rs
Labels: enhancement

#681 feat: tracing for http transports
  crates/transport-http/Cargo.toml
  crates/transport-http/src/hyper.rs
  crates/transport-http/src/reqwest.rs
Labels: enhancement, debt

#689 fix: add check before allocation in `SimpleCoder::decode_one()`
  crates/consensus/src/transaction/eip4844/builder.rs
Labels: enhancement

#694 fix: use U64 for feeHistory blocknumber
  crates/provider/src/provider/trait.rs
Labels: bug

#693 chore: rename `DepositReceipt` to `DepositRequest`
  crates/eips/src/eip6110.rs
  crates/rpc-types-engine/src/lib.rs
  crates/rpc-types-engine/src/payload.rs
Labels: debt

#695 feat: impl `From` for exec payload v4
  crates/rpc-types-engine/src/payload.rs
Labels: enhancement

#698 chore: actually impl from for payload v4
  crates/rpc-types-engine/src/payload.rs
Labels: enhancement

#676 feat: add `EngineApi` extension trait
  crates/provider/Cargo.toml
  crates/provider/src/ext/admin.rs
  crates/provider/src/ext/engine.rs
  crates/provider/src/ext/mod.rs
Labels: enhancement

#706 fix: account for requests root in header mem size
  crates/consensus/src/header.rs
Labels: bug

#705 feat: rlp for eip-7002 requests
  crates/eips/src/eip7002.rs
Labels: enhancement

#704 feat: add eip-7685 enc/decode traits
  crates/eips/src/eip7685.rs
  crates/eips/src/lib.rs
Labels: enhancement

#707 feat: add eth mainnet EL requests envelope
  crates/consensus/src/lib.rs
  crates/consensus/src/request.rs
  crates/eips/src/eip6110.rs
  crates/eips/src/eip7002.rs
Labels: enhancement

#716 feat: re-export and more http aliases
  crates/transport-http/src/hyper_transport.rs
  crates/transport-http/src/lib.rs
  crates/transport-http/src/reqwest_transport.rs
Labels: enhancement

#729 feat: derive arbitrary for `Request`
  crates/consensus/src/request.rs
Labels: enhancement

#731 feat: serde for `Request`
  crates/consensus/src/request.rs
Labels: enhancement

#732 feat: derive proptest arbitrary for `Request`
  crates/consensus/Cargo.toml
  crates/consensus/src/request.rs
Labels: enhancement

#674 RpcWithBlock
  crates/contract/src/call.rs
  crates/provider/Cargo.toml
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/lib.rs
  crates/provider/src/provider/call.rs
  crates/provider/src/provider/mod.rs
  crates/provider/src/provider/trait.rs
  crates/provider/src/provider/with_block.rs
  crates/provider/src/utils.rs
  crates/rpc-client/src/call.rs
Labels: enhancement, debt

#747 feat(eips): EIP-2935 history storage contract
  crates/eips/src/eip2935.rs
  crates/eips/src/lib.rs
Labels: enhancement

#751 chore: remove rlp encoding for `Request`
  crates/consensus/src/request.rs
Labels: debt

#757 feat: block id convenience functions
  crates/provider/src/provider/with_block.rs
Labels: enhancement

#763 refactor: improve eth_call internals
  crates/provider/src/provider/call.rs
Labels: bug, enhancement, debt

#765 update clippy warnings
  crates/consensus/src/sealed.rs
  crates/contract/src/call.rs
  crates/contract/src/eth_call.rs
  crates/contract/src/event.rs
  crates/contract/src/instance.rs
  crates/json-rpc/src/request.rs
  crates/json-rpc/src/result.rs
  crates/provider/src/provider/call.rs
  crates/provider/src/provider/with_block.rs
  crates/pubsub/src/sub.rs
  crates/rpc-types/src/eth/filter.rs
Labels: enhancement

#769 test: add another fee history serde test
  crates/rpc-types/src/eth/fee.rs
Labels: enhancement

#782 docs: move rpc client from transport readme
  crates/rpc-client/README.md
  crates/rpc-client/src/lib.rs
  crates/transport/README.md
Labels: enhancement

#783 fix: overrides are B256
  crates/rpc-types/src/eth/state.rs
Labels: bug

#786 Feat: HttpConnect
  crates/transport-http/src/hyper_transport.rs
  crates/transport-http/src/lib.rs
  crates/transport-http/src/reqwest_transport.rs
Labels: debt

#790 feat: fromiterator for filterset
  crates/rpc-types/src/eth/filter.rs
Labels: enhancement
