Repository alloy-rs/alloy, pull requests merged in 2025-04, with the labels that each got.

#2281 fix: cell proofs in `BlobsBundleV2::take`
  crates/rpc-types-engine/src/payload.rs
Labels: bug

#2282 feat: add `From<TxHash>` for `PendingTxConfig`
  crates/provider/src/heart.rs
Labels: enhancement, c-provider

#2285 feat: add eth get transaction by sender and nonce
  crates/provider/src/fillers/mod.rs
  crates/provider/src/provider/erased.rs
  crates/provider/src/provider/trait.rs
Labels: enhancement, c-provider

#2184 chore(deps): core 1.0
  Cargo.toml
  crates/consensus/src/signed.rs
  crates/consensus/src/transaction/eip1559.rs
  crates/consensus/src/transaction/eip2930.rs
  crates/consensus/src/transaction/eip4844.rs
  crates/consensus/src/transaction/eip7702.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/legacy.rs
  crates/consensus/src/transaction/rlp.rs
  crates/consensus/src/transaction/typed.rs
  crates/contract/src/call.rs
  crates/contract/src/error.rs
  crates/contract/src/eth_call.rs
  crates/contract/src/event.rs
  crates/contract/src/instance.rs
  crates/contract/src/interface.rs
  crates/contract/src/lib.rs
  crates/contract/src/multicall.rs
  crates/json-rpc/src/response/error.rs
  crates/network/src/ethereum/builder.rs
  crates/network/src/ethereum/wallet.rs
  crates/provider/src/layers/batch.rs
  crates/provider/src/provider/eth_call/mod.rs
  crates/provider/src/provider/multicall/inner_types.rs
  crates/provider/src/provider/multicall/mod.rs
  crates/provider/src/provider/multicall/tuple.rs
  crates/provider/src/provider/trait.rs
  crates/rpc-types-eth/src/log.rs
  crates/rpc-types-eth/src/transaction/receipt.rs
  crates/signer-aws/src/signer.rs
  crates/signer-gcp/src/signer.rs
  crates/signer-ledger/src/signer.rs
  crates/signer-local/src/lib.rs
  crates/signer-trezor/src/signer.rs
  crates/signer/src/lib.rs
  crates/signer/src/signer.rs
Labels: enhancement, blocked, breaking

#2225 chore(`provider`)!: rename `on_*` to `connect_*`
  crates/contract/src/call.rs
  crates/contract/src/error.rs
  crates/contract/src/event.rs
  crates/contract/src/instance.rs
  crates/contract/src/multicall.rs
  crates/provider/src/builder.rs
  crates/provider/src/ext/admin.rs
  crates/provider/src/ext/anvil.rs
  crates/provider/src/ext/debug.rs
  crates/provider/src/ext/net.rs
  crates/provider/src/ext/trace/mod.rs
  crates/provider/src/ext/txpool.rs
  crates/provider/src/fillers/chain_id.rs
  crates/provider/src/fillers/gas.rs
  crates/provider/src/fillers/nonce.rs
  crates/provider/src/fillers/wallet.rs
  crates/provider/src/layers/batch.rs
  crates/provider/src/layers/cache.rs
  crates/provider/src/provider/erased.rs
  crates/provider/src/provider/get_block.rs
  crates/provider/src/provider/multicall/mod.rs
  crates/provider/src/provider/trait.rs
  crates/provider/src/provider/wallet.rs
  crates/provider/src/provider/web3_signer.rs
  crates/provider/tests/it/mock.rs
  crates/provider/tests/it/ws.rs
Labels: breaking

#2317 update gcloud-sdk to 0.27
  Cargo.toml
Labels: blocked

#2301 feat(transport-ws): expose Ws url
  crates/transport-ws/src/native.rs
  crates/transport-ws/src/wasm.rs
Labels: blocked, breaking, c-transport
